### ISSUE TITLE
upgrade mongo to newer version, now I get 2.6.10

### ISSUE THREAD

**Issue by hiwjcn** [dockhippie/mongodb#14]
thanks

**Comment by tboerger** [comment]
What do you want now?

**Comment by hiwjcn** [comment]
how about upgrade mongodb to 3.x+ :)

**Comment by tboerger** [comment]
I have no idea how you get to 2.6.10, this image is running on 4.0 for quite some time already:

```
# docker run -ti --rm webhippie/mongodb:latest mongod --version
db version v4.0.9
git version: fc525e2d9b0e4bceff5c2201457e564362909765
OpenSSL version: OpenSSL 1.1.0g  2 Nov 2017
allocator: tcmalloc
modules: none
build environment:
    distmod: ubuntu1804
    distarch: x86_64
    target_arch: x86_64
```

**Comment by hiwjcn** [comment]
I tried on my raspberry pi (arm 32bit system) two weeks ago,
db.getversion()==2.6.10

now I have a work around for this issue, so I closed it.
thanks for your contribution anyway. 👍
