### ISSUE TITLE
Unrecognized env variable

### ISSUE THREAD

**Issue by yllekz** [dockhippie/mongodb#20]
Hello, I attempted to run this container with a few of the specified environment variables:

```
        environment:
            - MONGODB_SSL_ALLOW_CONNECTIONS_WITHOUT_CERTIFICATES=true
            - MONGODB_SSL_ALLOW_INVALID_CERTIFICATES=true
            - MONGODB_SSL_ALLOW_INVALID_HOSTNAMES=true
```

It resulted in these errors:

```
> starting mongodb service

Error parsing command line: unrecognised option '--sslAllowConnectionsWithoutCertificates'

try 'mongod --help' for more information
```

If I comment out ``- MONGODB_SSL_ALLOW_CONNECTIONS_WITHOUT_CERTIFICATES=true`` then the container is able to start.

Are the environment variables correct?

**Comment by tboerger** [comment]
I will come up with a new image, part of that will also be multiple tags for each minor and major version starting by 4.0

**Comment by tboerger** [comment]
After merging https://github.com/dockhippie/mongodb/pull/21 all valid environment variables should be listed on the readme.
