### ISSUE TITLE
The backup script fails on 6.0

### ISSUE THREAD

**Issue by krzys-h** [dockhippie/mongodb#72]
```sh
$ docker run --rm webhippie/mongodb:6.0
$ docker exec container_name backup
/usr/bin/backup: line 27: mongo: command not found
```

This worked fine on `5.0`.

Just replacing `mongo` with `mongosh` in the backup script seems to work (in the place where uses it to query list of databases, `mongodump` works normally). There are a bunch more occurrences in the `healthcheck` and `container` (for setting passwords) scripts, so I presume more things may be broken.

**Comment by tboerger** [comment]
Thanks for the report, took me some days to find the time for debugging. The new image should be pushed soonish which includes a fix.
